# Generated by Django 3.2.4 on 2021-06-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
